# Important suggestion for Cloudflare users or any other DNS/CDN which caches pages:
# To reduce the network/system load even more (by a massive amount), consider enabling page caching "/pages/*" and "/" (no *, just the homepage) in the dashboard.
# Enable "Respect strong ETags" in cache rules if you are going to enable page caching.
# DEFINETLY do these if you are running this in a cheap VPS and/or have low-bandwith.

port: 8080
#How many recent pages to show on the home page when the page loads.
cardsInHome: 20

#Path to cert any cert key. If left empty and no domains are added it will self sign.
certPath: ""
keyPath: ""
#Path to watch for markdown file changes. Can be relative.
mdPath: "mdFiles"

siteName: "My Site"
logoPath: ""
faviconPath: ""
description: "My site best site!"
overviewCharCount: 200
#LRU size: up to how many pages should Least Recently Used cache hold.
#Increasing this increases performance especially if you have a lot of pages. But it also increases RAM usage.
#You can assume increasing by 1 increases the max RAM usage by around 10KB for text-heavy articles or around 4KB for basic pages.
lruSize: 200

httpsMode: true
#To implement a ratelimit or not. You will probably not need it as Cloudflare/your DNS will take care of that for you.
ratelimit: false
replenishment: 6.0
burst: 30

#If you add domain(s) that point to this server, you can leave the cert and key path empty. Certmagic will get it for you.
#For Certmagic to get TLS certs, port setting must be at 443 and port 80 must also be accesable.
#domains: []
